
POST http://localhost:8080/api/alias HTTP/1/1
Content-Type: application/json

{
    "name": "Sherlock",
    "persona": "Holmes",
    "agentId": 1
}

#######


PUT http://localhost:8080/api/alias/1 HTTP/1/1
Content-Type: application/json

{

    "name": "Sherlock",
    "persona": null,
    "aliasId": 1
}

########

DELETE http://localhost:8080/api/alias/1 HTTP/1/1
Content-Type: application/json
